language: node_js
node_js:
 - "node"
notifications:
  email:
    - sftspider@gmail.com
deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    ci/cd: puppeteer-jest-travis-heroku
